### PR TITLE
Add new disambiguated text

### PR DESCRIPTION
**Pull request by albertonl**
New disambiguated text: /texts/olivertwist.raw.txt.
Have been added to apertium-spa.spa.dix the words _anheloso_, _utilísimo_, _borra_, _colchoncillo_, _Twist_, _desmayadamente_ and _boquear_.

### CODE REVIEW

**Comment by xavivars** [comment]
@albertonl, can you squash the commits? In your changes, you completely delete the Spanish monodix, and if we merge this pull request like it is know, it'll just "destroy" the file's history

**Comment by albertonl** [comment]
@xavivars, I did it like that because the file was too big and the GitHub editor didn't let me edit it, so I have edited it in local and then uploaded to GitHub changing it by the original one. Could you tell me a better solution please?

**Comment by xavivars** [comment]
The ideal scenario when you have to work offline is to "clone" the git repo (executing "git clone https://github.com/apertium/apertium-spa" locally). After that, you can modify anything you need in a git branch in your machine, and then create the pull request. I'm not sure how familiar you are with git. Github has pretty good documentation about it.

**Comment by xavivars** [comment]
Changes also in #2

**Pull request closed without merging**
