### PR TITLE
Add 10 new rules - albertonl

### PR DESCRIPTION
**Pull request by albertonl**
Added 10 Constraint Grammar rules.
See `#apertium` in `apertium-spa.spa.rlx` (lines 1278-1289).

### CODE REVIEW

**Comment by ftyers** [comment]
Can you add a full example sentence for each rule?

**Comment by albertonl** [comment]
In the rlx, here or in another file?

**Comment by ftyers** [comment]
In the rlx file :)

**Comment by xavivars** [comment]
Quick question (not strictly related to the task, but somehow): were these actual errors done by the spa tagger?

For example, this one should be working ok already

`SELECT Det IF (0 Det) (0 Pron) (1 N) ; # "La manzana me gusta mucho" (Appropriate structure: Det N Prn Vblex Adv) -> ^la/el<det><def><f><sg>$ ^manzana/manzana<n><f><sg>$`

The reason I ask is we've seen how adding CG rules slows down the translation process quite a lot, and I wouldn't want to add rules if there's no actual improvement compared to the previous output after the tagger.

**Comment by xavivars** [comment]
(Jaume commented before I did :) )

**Comment by albertonl** [comment]
@jaumeortola That's because I have put the tagged text using these rules. Should I put the original ones?
@xavivars I think that one I should change it by something as: `REMOVE Prn IF (0 "la" OR "La") (1 N) ;`, because "la" is tagged as `^la/el<det><def><f><sg>/lo<prn><pro><p3><f><sg>$`, so I thought that all determiners were wrongly tagged. Is this solution right?

**Comment by jaumeortola** [comment]
I checked your sentences _without_ your rules, and all the tagger results are fine.

`$ echo "La manzana me gusta mucho." | apertium -d . spa-cat-tagger`
`^El<det><def><f><sg>$ ^manzana<n><f><sg>$ ^me<prn><pro><p1><mf><sg>$ ^gustar<vblex><pri><p3><sg>$ ^mucho<adj><m><sg>$^.<sent>$^.<sent>$`

With "la" (only singular) the problem is the same. If the next word is a noun and a verb (la cosa, la coma, la caza...) you cannot infer the correct tags, so it is better to let the tagger (or other more complex rules) decide. 
 
Please give us examples of wrongly tagged sentences.

Remember:
`spa-cat-morph` shows all the tags assigned by the dictionary.
`spa-cat-disam` shows the results of CG rules. 
`spa-cat-tagger`shows the tagger output.

**Comment by albertonl** [comment]
@jaumeortola These are example wrongly tagged sentences (_without_ my rules):

- **Rule 1:** _una cuarta parte de la bolsa_ (_la bolsa_ -> `^la/el<det><def><f><sg>/lo<prn><pro><p3><f><sg>$ ^bolsa/bolsa<n><f><sg>$`).
- **Rule 2:** _Cuando me quise dar cuenta..._ (_quise dar cuenta_ ("querer dar(se) cuenta") -> `^quise/querer<vblex><ifi><p1><sg>/querer<vbmod><ifi><p1><sg>$ ^dar cuenta/dar<vblex><inf># cuenta$`).
- **Rule 3:** _aún cabía la posibilidad de que mamá no lo notara_ (_lo notara_ -> `^lo/lo<detnt>/lo<prn><pro><p3><nt>/lo<prn><pro><p3><m><sg>$ ^notara/notar<vblex><pis><p3><sg>/notar<vblex><pis><p1><sg>$`).
- **Rule 4:** _me había comido una cuarta parte de la bolsa_ (_me había comido_-> `^me/me<prn><pro><p1><mf><sg>$ ^había/haber<vbhaver><pii><p3><sg>/haber<vbhaver><pii><p1><sg>/haber<vblex><pii><p3><sg>$ ^comido/comer<vblex><pp><m><sg>/comedir<vblex><pri><p1><sg>$`).
- **Rule 5:** _la bolsa se había agrandado_ (_había agrandado_ (acting on "agrandado") -> `^había/haber<vbhaver><pii><p3><sg>/haber<vbhaver><pii><p1><sg>/haber<vblex><pii><p3><sg>$ ^agrandado/agrandar<vblex><pp><m><sg>$`).
- **Rule 6:** _Pensé que aún cabía la posibilidad_ (_cabía la posibilidad_ -> `^cabía/caber<vblex><pii><p3><sg>/caber<vblex><pii><p1><sg>$ ^la/el<det><def><f><sg>/lo<prn><pro><p3><f><sg>$ ^posibilidad/posibilidad<n><f><sg>$`).
- **Rule 7:** _...de que mamá no lo notara_ (_lo notara_ -> `^lo/lo<detnt>/lo<prn><pro><p3><nt>/lo<prn><pro><p3><m><sg>$ ^notara/notar<vblex><pis><p3><sg>/notar<vblex><pis><p1><sg>$`).
- **Rule 8:** _...y algo tenía que hacer_ (_algo tenía que_ -> `^algo/algo<preadv>/algo<adj><m><sg>/algo<prn><tn><nt><sg>$ ^tenía que/tener<vbmod><pii><p3><sg># que/tener<vbmod><pii><p1><sg># que$`).
- **Rule 9:** _hice la gran compra del mes_ (_la gran compra_ -> `^la/el<det><def><f><sg>/lo<prn><pro><p3><f><sg>$ ^gran/gran<adj><mf><sg>$ ^compra/compra<n><f><sg>/comprar<vblex><pri><p3><sg>/comprar<vblex><imp><p2><sg>$`).
- **Rule 10:** _Tienen un sabor amargo_ (_sabor amargo_ (acting on "amargo") -> `^sabor/sabor<n><m><sg>$ ^amargo/amargo<adj><m><sg>/amargar<vblex><pri><p1><sg>$`).

**Comment by albertonl** [comment]
Also, while I was writing the comment I have modified the rules to adjust better to the requirements.

**Comment by jaumeortola** [comment]
You are sending the results of "morph", with all the tags assigned by the dictionary:
`$ echo "de la bolsa." | apertium -d . spa-cat-morph`
`^de/de<pr>$ ^la/el<det><def><f><sg>/lo<prn><pro><p3><f><sg>$ ^bolsa/bolsa<n><f><sg>$^./.<sent>$^./.<sent>$`

That is not what we need. We need the tagger results, which are perfectly fine, as you can see here:
`$ echo "de la bolsa." | apertium -d . spa-cat-tagger`
`^de<pr>$ ^el<det><def><f><sg>$ ^bolsa<n><f><sg>$^.<sent>$^.<sent>$`

How are you generating these analyses?

**Comment by albertonl** [comment]
Oh, sorry. I was generating the analyses with `spa-cat-morph`, so I thought there were more ambiguities than what I expected.
So I will repeat the rules but now using `spa-cat-tagger`. And just a little question: the CG rules are generalized or there are some specific rules for each word?

**Comment by albertonl** [comment]
Should I do it like that?

**Comment by jaumeortola** [comment]
First of all, find wrongly tagged sentences by the tagger. Perhaps I can provide some, but they will be quite difficult to solve.

**Comment by albertonl** [comment]
Done.

**Comment by albertonl** [comment]
If you are interested, I have written a simple report of the update in my web page:
[ProShare](projectmanager.x10host.com)

**Comment by albertonl** [comment]
If you are interested, you can see a little report I wrote in my web page:
projectmanager.x10host.com/apertium/home.html

**Comment by albertonl** [comment]
If you are interested, I have written a little report in my web page:
proshare.x10host.com

**Comment by jaumeortola** [comment]
The tags (`<adv>`) in your web page are not visible. 

I get different tagger results. For example, "no" is never tagged `<ij>`, because this tag is never used in the spa-cat dictionary. Perhaps you are using a different language pair? Why is "tocó" tagged `<p1>` (yo tocó)?...

Anyway, these rules don't seem interesting, and I think they won't be useful. 

If you want to do something useful, take a word like "solo", which is ambiguous (adv/adj), and study it in a corpus. See when the tagger fails, and see if the errors can be fixed with some CG rules.

**Pull request closed without merging**
